name: Notify Slack

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: '{"text": "A new change has been pushed to main or a PR has been merged!"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
